### ISSUE TITLE
[Not sure] SVS Sync Interest with multicast forwarding hint

### ISSUE THREAD

**Issue by zjkmxy** [UCLA-IRL/ndn-workspace-solid#17]
Since NDN testbed only has `/ndn/multicast` set to use the multicast strategy by default, to make our app work we had to make the whole workspace prefix be under `/ndn/multicast`. But this also multicasts Data Interests.
We want to support arbitrary workspace prefix. Maybe we should use forwarding hints to multicast SVS Sync Interests?

**Comment by yoursunny** [comment]
> Since NDN testbed only has `/ndn/multicast` set to use the multicast strategy by default, to make our app work we had to make the whole workspace prefix be under `/ndn/multicast`. But this also multicasts Data Interests.

Sync group prefix and application data prefix can be chosen independently.
As an example, StateVectorSync C++ library `chat` example uses a sync group prefix that starts with `/ndn/svs` and allows each participant to choose a different prefix for published application data.

**Comment by zjkmxy** [comment]
That leads back to the discussion on application namespace vs forwarding namespace...
This app uses application namespace for security and management, so all forwarding related thing should be expressed in ForwardingHints.

**Comment by yoursunny** [comment]
I'm afraid NFD would not treat `ForwardingHint: /ndn/multicast` as multicast Interest.
StrategyChoice lookup is based on PIT entry name i.e. Interest name, and ForwardingHint is not considered whatsoever.
Thus, the effective strategy would be whatever strategy that matches the Interest name.

NDNts side should be okay.
If you invoke `fw.nodeNames.append(new Name("/ndn/multicast"))`, NDNts FIB lookup will use Interest name, so that incoming Interest with this ForwardingHint can reach the correct producer handler.

**Comment by zjkmxy** [comment]
After discussion we think this is not the correct way to do things.
